[versions]
appVersionCode = "615"
appVersionName = "1.36"
androidGradlePlugin = "9.3.2"
kotlin = "2.4.10"
dagger = "2.60.1"
ksp = "2.3.11"
ideaExt = "1.4.1"
androidxBaselineProfile = "1.5.0-rc02"
androidxCore = "1.19.0"
androidxCoreI18n = "1.0.0"
androidxAppCompat = "1.8.0"
androidxActivity = "1.13.0"
androidxFragment = "1.9.0"
androidxBrowser = "1.10.0"
androidxMedia3 = "1.11.0"
androidxMedia = "1.7.1"
androidxMediaRouter = "1.8.1"
androidxWebkit = "1.15.0"
androidxCollection = "1.6.0"
androidxLifecycle = "2.11.0"
androidxNavigation3 = "1.1.7"
androidxHiltNavCompose = "1.4.0"
androidxSplashScreen = "1.2.0"
androidxPaging = "3.5.1"
androidxStartup = "1.2.0"
androidxDatastorePref = "1.2.1"
androidxAnnotation = "1.10.0"
androidxProfileInstaller = "1.4.1"
androidxComposeBom = "2026.08.00"
androidxTvMaterial = "1.1.0"
androidxTest = "1.7.0"
androidxTestJunit = "1.3.0"
androidxEspresso = "3.7.0"
androidxUiautomator = "2.4.0"
androidxBenchmarkJunit4 = "1.4.1"
googleCast = "22.3.1"
googleCastTv = "21.1.1"
reorderable = "3.1.0"
retrofit = "3.0.0"
kotlinxSerialization = "1.11.0"
kotlinxCoroutines = "1.11.0"
okhttp3 = "5.5.0"
coil = "3.5.0"
timber = "5.0.1"
leakcanary = "2.14"
desugarJdkLibs = "2.1.5"
junit = "4.13.2"
mockk = "1.14.11"
assertk = "0.28.1"
jsonassert = "1.5.3"
processPhoenix = "3.0.0"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-core-i18n = { module = "androidx.core:core-i18n", version.ref = "androidxCoreI18n" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppCompat" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidx-fragment-compose = { module = "androidx.fragment:fragment-compose", version.ref = "androidxFragment" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidxBrowser" }
androidx-media3 = { module = "androidx.media3:media3-exoplayer", version.ref = "androidxMedia3" }
androidx-media3-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "androidxMedia3" }
androidx-media = { module = "androidx.media:media", version.ref = "androidxMedia" }
androidx-mediarouter = { module = "androidx.mediarouter:mediarouter", version.ref = "androidxMediaRouter" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "androidxWebkit" }
androidx-collection = { module = "androidx.collection:collection", version.ref = "androidxCollection" }
androidx-lifecycle-vm = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-vm-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "androidxLifecycle" }
androidx-lifecycle-vm-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidxLifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidxLifecycle" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "androidxNavigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "androidxNavigation3" }
androidx-hilt-nav-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHiltNavCompose" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxSplashScreen" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidxPaging" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidxStartup" }
androidx-datastore-pref = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDatastorePref" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidxProfileInstaller" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics-android" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite" }
androidx-compose-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-tv-material = { module = "androidx.tv:tv-material", version.ref = "androidxTvMaterial" }
androidx-test = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidxTestJunit" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidxUiautomator" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspresso" }
androidx-benchmark-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidxBenchmarkJunit4" }
google-cast-framework = { module = "com.google.android.gms:play-services-cast-framework", version.ref = "googleCast" }
google-cast = { module = "com.google.android.gms:play-services-cast", version.ref = "googleCast" }
google-cast-tv = { module = "com.google.android.gms:play-services-cast-tv", version.ref = "googleCastTv" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
dagger-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-kotlinx-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlin-metadata-jvm = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version.ref = "kotlin" }
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
okhttp3-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }
okhttp3-tls = { module = "com.squareup.okhttp3:okhttp-tls", version.ref = "okhttp3" }
okhttp3-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp3" }
coil-bom = { module = "io.coil-kt.coil3:coil-bom", version.ref = "coil" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg" }
coil-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp" }
coil-cachecontrol = { module = "io.coil-kt.coil3:coil-network-cache-control" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
process-phoenix = { module = "com.jakewharton:process-phoenix", version.ref = "processPhoenix" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }
junit = { module = "junit:junit", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
jsonassert = { module = "org.skyscreamer:jsonassert", version.ref = "jsonassert" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidxBaselineProfile"}
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "ideaExt" }
