name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:
    inputs:
      pr:
        description: "PR # (optional)"
        required: false
        type: number

concurrency:
  # Limit concurrency to 1 for PRs. 'main' concurrency isn't limited.
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with: &setup-checkout
          ref: ${{ inputs.pr && format('refs/pull/{0}/head', inputs.pr) || github.sha }}
      - uses: ./.github/actions/setup-build
        with: &setup-build-inputs
          keystore: ${{ secrets.KEYSTORE_FILE_BASE64 }}
          keystore-passphrase: ${{ secrets.KEYSTORE_FILE_PASSPHRASE }}
          keystore-password: ${{ secrets.KEYSTORE_PASSWORD }}
          key-alias: ${{ secrets.UPLOAD_KEY_ALIAS }}
          key-password: ${{ secrets.UPLOAD_KEY_PASSWORD }}
          rainwave-test-creds: ${{ secrets.RAINWAVE_TEST_CREDENTIALS }}
      - uses: android-actions/setup-android@v4
        with:
          log-accepted-android-sdk-licenses: false
      - run: ./gradlew lint
      - name: Lint Summary
        uses: hidakatsuya/action-report-android-lint@v1.3.0
        if: always()
        with:
          result-path: 'app/build/reports/**/lint-results-*.xml'

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with: *setup-checkout
      - uses: ./.github/actions/setup-build
        with: *setup-build-inputs
      - run: ./gradlew test
      - name: Unit tests summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: |
            app/build/test-results/**/TEST-*.xml

  assemble:
    name: Assemble apk/aab
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with: *setup-checkout
      - uses: ./.github/actions/setup-build
        with: *setup-build-inputs
      - name: Build AAB with Gradle
        run: ./gradlew bundleRelease
      - name: Build universal APK from AAB
        run: |
          json=$(curl -s https://api.github.com/repos/google/bundletool/releases/latest)
          downloadUrl=$(echo $json | jq -r ".assets | .[].browser_download_url")
          curl $downloadUrl -4 -sL -o 'bundletool.jar'
          java -jar bundletool.jar build-apks --bundle=app/build/outputs/bundle/release/app-release.aab --output=app.apks \
            --mode=universal \
            --ks=app/keystore.jks \
            --ks-pass=pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --ks-key-alias=${{ secrets.RELEASE_KEY_ALIAS }} \
            --key-pass=pass:${{ secrets.RELEASE_KEY_PASSWORD }}
          unzip app.apks -d .
          mkdir -p app/build/outputs/apk/release
          mv universal.apk app/build/outputs/apk/release/app-release.apk
      - name: Upload apk/aab
        uses: actions/upload-artifact@v7
        with:
          name: artifact
          path: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/bundle/release/app-release.aab
          if-no-files-found: error

  release:
    needs: [lint, unit-tests, assemble]
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: dist
          name: artifact
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            dist/**/*.apk
            dist/**/*.aab
